# Generated by Django 5.1.7 on 2025-05-15 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('USER', 'User'), ('DENTIST', 'Dentist'), ('ADMIN', 'Admin')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('SYSTEM', 'System'), ('SECURITY', 'Security'), ('EVENT', 'Event'), ('EMERGENCY', 'Emergency')], max_length=10)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField()),
                ('age', models.PositiveIntegerField(default=0)),
                ('sex', models.CharField(default=None, max_length=10)),
                ('religion', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=100)),
                ('dental_insurance', models.CharField(blank=True, max_length=254, null=True)),
                ('dental_insurance_effective_date', models.DateField(blank=True, null=True)),
                ('for_minors_parent_or_guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('for_minors_parent_or_guardian_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('home_no', models.CharField(blank=True, max_length=255, null=True)),
                ('office_no', models.CharField(blank=True, max_length=255, null=True)),
                ('fax_no', models.CharField(blank=True, max_length=255, null=True)),
                ('cel_mobile_no', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('referral_thanks', models.CharField(blank=True, max_length=255, null=True)),
                ('dental_consultation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('prev_dentist', models.CharField(blank=True, max_length=255, null=True)),
                ('last_dental_visit', models.CharField(blank=True, max_length=255, null=True)),
                ('physician_name', models.CharField(blank=True, max_length=255, null=True)),
                ('physician_specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('physician_office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('physician_office_no', models.CharField(blank=True, max_length=255, null=True)),
                ('mi_isgoodhealth', models.CharField(default=None, max_length=3)),
                ('mi_is_under_medical_treatment', models.CharField(default=None, max_length=3)),
                ('mi_is_under_medical_treatment_followup', models.CharField(blank=True, max_length=255, null=True)),
                ('mi_is_serious_illness', models.CharField(default=None, max_length=3)),
                ('mi_is_serious_illness_followup', models.CharField(blank=True, max_length=255, null=True)),
                ('mi_is_hospitalized', models.CharField(default=None, max_length=3)),
                ('mi_is_hospitalized_folloup', models.CharField(blank=True, max_length=255, null=True)),
                ('mi_is_taking_prescription', models.CharField(default=None, max_length=3)),
                ('mi_is_taking_prescription_followup', models.CharField(blank=True, max_length=255, null=True)),
                ('mi_is_using_tobacco', models.CharField(default=None, max_length=3)),
                ('mi_is_using_dangerous_drugs', models.CharField(default=None, max_length=3)),
                ('mi_is_allergic', models.JSONField(blank=True, default=list, null=True)),
                ('mi_is_allergic_others', models.CharField(blank=True, max_length=255, null=True)),
                ('mi_bleeding_time', models.CharField(blank=True, max_length=255, null=True)),
                ('mi_is_pregnant', models.CharField(blank=True, max_length=3, null=True)),
                ('mi_is_nursing', models.CharField(blank=True, max_length=3, null=True)),
                ('mi_is_birth_control', models.CharField(blank=True, max_length=3, null=True)),
                ('mi_bloodtype', models.CharField(max_length=255)),
                ('mi_bloodpressure', models.CharField(max_length=255)),
                ('mi_select_disease', models.JSONField(blank=True, default=list, null=True)),
                ('mi_select_disease_others', models.CharField(blank=True, max_length=255, null=True)),
                ('synced_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntraoralExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teeth', models.JSONField(blank=True, default=list, null=True)),
                ('xray_taken', models.JSONField(blank=True, default=list, null=True)),
                ('xray_periapical', models.CharField(blank=True, max_length=255, null=True)),
                ('xray_taken_others', models.CharField(blank=True, max_length=255, null=True)),
                ('periodontal_screening', models.JSONField(blank=True, default=list, null=True)),
                ('occlusion', models.JSONField(blank=True, default=list, null=True)),
                ('appliances', models.JSONField(blank=True, default=list, null=True)),
                ('appliances_others', models.CharField(blank=True, max_length=255, null=True)),
                ('tmd', models.JSONField(blank=True, default=list, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dental.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('dentist', models.ForeignKey(limit_choices_to={'role': 'DENTIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Scheduled', max_length=50)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('dentist', models.ForeignKey(limit_choices_to={'role': 'DENTIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.TextField()),
                ('dosage', models.TextField()),
                ('instructions', models.TextField()),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.patient')),
                ('prescribed_by', models.ForeignKey(limit_choices_to={'role': 'DENTIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField(null=True)),
                ('tooth_number', models.IntegerField(null=True)),
                ('treatment_procedure', models.TextField(null=True)),
                ('treatment_dentist', models.CharField(max_length=255, null=True)),
                ('amount_charged', models.IntegerField(null=True)),
                ('amount_paid', models.IntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('next_appointment', models.DateField(max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.patient')),
            ],
        ),
    ]
