# Generated by Django 5.1.7 on 2025-05-09 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_patients', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DentistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('birthdate', models.DateField()),
                ('age', models.PositiveIntegerField(default=0)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=10)),
                ('religion', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=100)),
                ('dental_insurance', models.CharField(blank=True, max_length=254, null=True)),
                ('dental_insurance_effective_date', models.DateField(blank=True, null=True)),
                ('for_minors_parent_or_guardian_name', models.CharField(max_length=255)),
                ('for_minors_parent_or_guardian_occupation', models.CharField(max_length=100)),
                ('home_no', models.CharField(max_length=255, null=True)),
                ('fax_no', models.CharField(max_length=255, null=True)),
                ('cel_mobile_no', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('referral_thanks', models.CharField(max_length=255, null=True)),
                ('dental_consultation_reason', models.CharField(max_length=255, null=True)),
                ('prev_dentist', models.CharField(max_length=255, null=True)),
                ('last_dental_visit', models.CharField(max_length=255, null=True)),
                ('physician_name', models.CharField(max_length=255, null=True)),
                ('physician_specialty', models.CharField(max_length=255, null=True)),
                ('office_address', models.CharField(max_length=255, null=True)),
                ('office_no', models.CharField(max_length=255, null=True)),
                ('mi_isgoodhealth', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=255)),
                ('mi_is_under_medical_treatment', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=255)),
                ('mi_is_under_medical_treatment_followup', models.CharField(max_length=255, null=True)),
                ('mi_is_serious_illness', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=255)),
                ('mi_is_serious_illness_followup', models.CharField(max_length=255, null=True)),
                ('mi_is_hospitalized', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=255)),
                ('mi_is_hospitalized_folloup', models.CharField(max_length=255, null=True)),
                ('mi_is_taking_prescription', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=255)),
                ('mi_is_taking_prescription_followup', models.CharField(max_length=255, null=True)),
                ('mi_is_using_tobacco', models.CharField(default=None, max_length=255)),
                ('mi_is_allergic', models.JSONField(choices=[('LOCAL ANESTHETIC', 'Local Anesthetic (ex. Lidocaine)'), ('PENICILIN, ANTIBIOTICS', 'Penicilin, Antibiotics'), ('SULFA DRUGS', 'Sulfa Drugs'), ('ASPIRIN', 'Aspirin'), ('LATEX', 'Latex'), ('OTHERS', 'Others')], default=list, null=True)),
                ('mi_is_allergic_others', models.CharField(max_length=255, null=True)),
                ('mi_bleeding_time', models.CharField(max_length=255)),
                ('mi_is_pregnant', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=255)),
                ('mi_is_nursing', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=255)),
                ('mi_is_birth_control', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=255)),
                ('mi_bloodtype', models.CharField(max_length=255)),
                ('mi_bloodpressure', models.CharField(max_length=255)),
                ('mi_select_disease', models.JSONField(choices=[('HIGH BLOOD PRESSURE', 'High Blood Pressure'), ('LOW BLOOD PRESSURE', 'Low Blood Pressure'), ('EPILEPSY/CONVULSIONS', 'Epilepsy / Conculsions'), ('AIDS OR HIV INFECTION', 'AIDS or HIV Infection'), ('SEXUALLY TRANSMITTED DISEASE', 'Sexually Transmitted Disease'), ('STOMACH TROUBLES / ULCERS', 'Stomach Troubles / Ulcers'), ('FAINTING SEIZURES', 'Fainting Seizures'), ('RAPID WEIGHT LOSS', 'Rapid Weight Loss'), ('RADIATION THERAPY', 'Radiation Therapy'), ('JOINT REPLACEMENT / IMPLANT', 'Joint Replacement / Implant'), ('HEART SURGERY', 'Heart Surgery'), ('HEART ATTACK', 'Heart Attack'), ('THYROID PROBLEM', 'Thyroid Problem'), ('HEART DISEASE', 'Heart Disease'), ('HEART MURMUR', 'Heart Murmur'), ('HEPATITIS / LIVER DISEASE', 'Hepatitis / Liver Disease'), ('RHEUMATIC FEVER', 'Rheumatic Fever'), ('HAY FEVER / ALLERGIES', 'Hay Fever / Allergies'), ('RESPIRATORY PROBLEMS', 'Respiratory Problems'), ('HEPATITIS / JAUNDICE', 'Hepatitis / Jaundice'), ('TUBERCULOSIS', 'Tuberculosis'), ('SWOLLEN ANKLES', 'Swollen Ankles'), ('KIDNEY DISEASE', 'Kidney Disease'), ('DIABETES', 'Diabetes'), ('CHEST PAIN', 'Chest Pain'), ('STROKE', 'Stroke'), ('CANCER / TUMORS', 'Cancer / Trumors'), ('ANEMIA', 'Anemia'), ('ANGINA', 'Angina'), ('ASTHMA', 'Asthma'), ('EMPHYSEMA', 'Empysema'), ('BLEEDING PROBLEMS', 'Bleeding Problems'), ('BLOOD DISEASES', 'Blood Diseases'), ('HEAD INJURIES', 'Head Injuries'), ('ARTHRITIS / RHEUMATISM', 'Arthritis / Rheumatism')], default=list, null=True)),
                ('mi_select_disease_others', models.CharField(max_length=255, null=True)),
                ('synced_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntraoralExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('dentist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dental.dentistprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_details', models.TextField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.patient')),
            ],
        ),
    ]
