# Generated by Django 5.1.7 on 2025-05-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_birth_control',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('Yes', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_hospitalized',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'No')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_nursing',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('Yes', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_pregnant',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('Yes', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_serious_illness',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'No')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_taking_prescription',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'No')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_under_medical_treatment',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'No')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_using_dangerous_drugs',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'No')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_using_tobacco',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'No')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_isgoodhealth',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'No')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10),
        ),
    ]
