# Generated by Django 5.1.7 on 2025-03-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0002_rename_user_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='user_firstname',
            new_name='patient_firstname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user_lastname',
            new_name='patient_lastname',
        ),
    ]
