# Generated by Django 5.1.7 on 2025-05-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0002_adminprofile_dentistprofile_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dental_consultation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fax_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_dental_visit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_bleeding_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_allergic',
            field=models.JSONField(blank=True, choices=[('LOCAL ANESTHETIC', 'Local Anesthetic (ex. Lidocaine)'), ('PENICILIN, ANTIBIOTICS', 'Penicilin, Antibiotics'), ('SULFA DRUGS', 'Sulfa Drugs'), ('ASPIRIN', 'Aspirin'), ('LATEX', 'Latex'), ('OTHERS', 'Others')], default=list, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_allergic_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_birth_control',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_hospitalized_folloup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_nursing',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_pregnant',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_serious_illness_followup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_taking_prescription_followup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_under_medical_treatment_followup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_select_disease',
            field=models.JSONField(blank=True, choices=[('HIGH BLOOD PRESSURE', 'High Blood Pressure'), ('LOW BLOOD PRESSURE', 'Low Blood Pressure'), ('EPILEPSY/CONVULSIONS', 'Epilepsy / Conculsions'), ('AIDS OR HIV INFECTION', 'AIDS or HIV Infection'), ('SEXUALLY TRANSMITTED DISEASE', 'Sexually Transmitted Disease'), ('STOMACH TROUBLES / ULCERS', 'Stomach Troubles / Ulcers'), ('FAINTING SEIZURES', 'Fainting Seizures'), ('RAPID WEIGHT LOSS', 'Rapid Weight Loss'), ('RADIATION THERAPY', 'Radiation Therapy'), ('JOINT REPLACEMENT / IMPLANT', 'Joint Replacement / Implant'), ('HEART SURGERY', 'Heart Surgery'), ('HEART ATTACK', 'Heart Attack'), ('THYROID PROBLEM', 'Thyroid Problem'), ('HEART DISEASE', 'Heart Disease'), ('HEART MURMUR', 'Heart Murmur'), ('HEPATITIS / LIVER DISEASE', 'Hepatitis / Liver Disease'), ('RHEUMATIC FEVER', 'Rheumatic Fever'), ('HAY FEVER / ALLERGIES', 'Hay Fever / Allergies'), ('RESPIRATORY PROBLEMS', 'Respiratory Problems'), ('HEPATITIS / JAUNDICE', 'Hepatitis / Jaundice'), ('TUBERCULOSIS', 'Tuberculosis'), ('SWOLLEN ANKLES', 'Swollen Ankles'), ('KIDNEY DISEASE', 'Kidney Disease'), ('DIABETES', 'Diabetes'), ('CHEST PAIN', 'Chest Pain'), ('STROKE', 'Stroke'), ('CANCER / TUMORS', 'Cancer / Trumors'), ('ANEMIA', 'Anemia'), ('ANGINA', 'Angina'), ('ASTHMA', 'Asthma'), ('EMPHYSEMA', 'Empysema'), ('BLEEDING PROBLEMS', 'Bleeding Problems'), ('BLOOD DISEASES', 'Blood Diseases'), ('HEAD INJURIES', 'Head Injuries'), ('ARTHRITIS / RHEUMATISM', 'Arthritis / Rheumatism')], default=list, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_select_disease_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='office_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='office_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='physician_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='physician_specialty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prev_dentist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='referral_thanks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
