# Generated by Django 5.1.7 on 2025-05-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='claimed_existing_patient',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_answered_existing_patient',
            field=models.BooleanField(default=False),
        ),
    ]
