# Generated by Django 5.1.7 on 2025-05-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0003_patient_claimed_existing_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.CharField(choices=[('Oral Exam', 'Oral Exam'), ('Oral Propelaxis', 'Oral Propelaxis'), ('Tooth Restoration', 'Tooth Restoration'), ('Tooth Extraction', 'Tooth Extraction'), ('Orthodontic Treatment', 'Orthodontic Treatment'), ('Minor Surgical Treatment', 'Minor Surgical Treatment'), ('Fluoride Application', 'Fluoride Application'), ('Prosthodontic Treatment', 'Prosthodontic Treatment')], max_length=50),
        ),
    ]
