# Generated by Django 5.1.7 on 2025-05-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0003_alter_patient_dental_consultation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mi_is_using_tobacco',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=255),
        ),
    ]
