# Generated by Django 5.1.7 on 2025-05-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0004_alter_appointment_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], db_index=True, default='Scheduled', max_length=20),
        ),
    ]
