# Generated by Django 5.1.7 on 2025-05-11 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0004_alter_patient_mi_is_using_tobacco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentistprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='intraoralexamination',
            name='dentist',
        ),
        migrations.RemoveField(
            model_name='intraoralexamination',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='intraoralexamination',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='treatmentrecord',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='treatmentrecord',
            name='treatment_details',
        ),
        migrations.AddField(
            model_name='intraoralexamination',
            name='appliances',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='intraoralexamination',
            name='appliances_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intraoralexamination',
            name='occlusion',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='intraoralexamination',
            name='periodontal_screening',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='intraoralexamination',
            name='tmd',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='intraoralexamination',
            name='xray_periapical',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intraoralexamination',
            name='xray_taken',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='intraoralexamination',
            name='xray_taken_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intraoralexamination',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dental.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='for_minors_parent_or_guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='for_minors_parent_or_guardian_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_allergic',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_birth_control',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_hospitalized',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_nursing',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_pregnant',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_serious_illness',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_taking_prescription',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_under_medical_treatment',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_is_using_tobacco',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_isgoodhealth',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mi_select_disease',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='DentistProfile',
        ),
    ]
