# Generated by Django 5.1.3 on 2025-05-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0005_remove_dentistprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='amount_charged',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='amount_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='next_appointment',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='tooth_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='treatment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='treatment_dentist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='treatment_procedure',
            field=models.TextField(null=True),
        ),
    ]
