# Generated by Django 5.1.3 on 2025-05-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='digital_xrays',
            field=models.ImageField(blank=True, null=True, upload_to='xrays/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_pictures',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_signatures',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='philhealth_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
