# Generated by Django 5.1.7 on 2025-05-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0006_patient_digital_xrays_patient_patient_pictures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Account', 'Account'), ('Appointment', 'Appointment'), ('Reminder', 'Reminder'), ('Prescription', 'Prescription'), ('Smart Suggestions', 'Smart Suggestions')], default='Account', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
