# Generated by Django 5.1.7 on 2025-05-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0007_notification_redirect_url_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Account', 'Account'), ('Appointment', 'Appointment'), ('Reminder', 'Reminder'), ('Prescription', 'Prescription'), ('Smart Suggestions', 'Smart Suggestions'), ('Emergency', 'Emergency')], default='Account', max_length=20),
        ),
    ]
